add more refactored services
gerardobrm/indio-services pull request #7
Opened 2023-04-27 18:43 UTC by Mariotroiano

2023-04-27 18:46 UTC, Mariotroiano commented on src/services/prkset/MessageService.ts
>    };
getById llama a getByReservationId, si lo saco va a dejar de funcionar dónde se use pero podría utilizarse directamente el getByReservationId

2023-04-27 18:47 UTC, Mariotroiano commented on src/services/prkset/OrdersService.ts
>      await makePatch(`/api/v1/guests/${id}`, payload);
"updatePartial" le pega a /guest. ¿Es un infiltrado y hay que eliminarlo? utilizamos el servicio de guest ahí dentro importandolo? o ¿reemplazo el "guest" por "orders"?

2023-04-27 18:48 UTC, Mariotroiano commented on src/services/prkset/ParkSettingsService.ts
> +}
cambio el "type GenericPayload" a "class GenericPayload" para poder crear la instancia de JsonApiClient. (Se supone que el Record de typescript sigue funcionando con un type, interface o class)

2023-04-27 18:51 UTC, Mariotroiano commented on src/services/prkset/ParkSettingsService.ts
>      const responses = await Promise.all(requests);
No pude sacar el makeGet de ParkSettingsService, necesitamos una clase para el ClassConstructor del JsonApiClient

2023-04-27 18:53 UTC, Mariotroiano commented on src/services/prkset/TaxService.ts
> +const taxTableclient = new JsonApiClient(TaxTablePayload, ax, 'tax_tables');
Se podrían separar los servicios que utilizan tax_table y pasa a su propio .ts ya existente "TaxTableService"

2023-04-27 18:54 UTC, Mariotroiano commented on src/services/prkset/SundriesService.ts
>    }
En SundriesService el método getById retorna un listado, no un item por lo tanto no utilizo el getById de JsonApiClient sino el find. Esto es correcto?

2023-04-27 18:56 UTC, Mariotroiano commented on src/services/prkset/VehicleLookupService.ts
> +const clientGenerator = (path: VehiclePath) => new JsonApiClient(VehicleLookupPayload, ax, path);
Con esta función creo una instancia de JsonApiClient para cada path pero al utilizar el método, esto es correcto? ejemplo: 

  static getTypes = async () => {
    const client = clientGenerator(VehiclePath.Types);
    const result = await client.find();
    return result;
  }

2023-05-01 23:26 UTC, gerardobrm requested changes

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/ChargeService.ts
> -  };
No quites estos métodos xq capaz se usan en algún lado...

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/OrdersService.ts
>      await makePatch(`/api/v1/guests/${id}`, payload);
Probablemente quedo de un copy & paste... Eliminalo

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/MessageService.ts
>    };
Dejalo como está

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/ParkSettingsService.ts
>      const responses = await Promise.all(requests);
Creo que este service quedó deprecado

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/SundriesService.ts
>    }
Sería correcto pero no sé xq devuelve un array

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/TaxService.ts
> +const taxTableclient = new JsonApiClient(TaxTablePayload, ax, 'tax_tables');
Seguramente, alguien no siguió la lógica de los otros servicios. Igualmente creo que tmb están deprecados...

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/VehicleLookupService.ts
> +      electricals: this.getElectricals(),
Acá no va `this` xq getLookups es static, todo es static...
Entonces hay q usarlo como estaba

2023-05-01 23:26 UTC, gerardobrm commented on src/services/prkset/VehicleLookupService.ts
> +const clientGenerator = (path: VehiclePath) => new JsonApiClient(VehicleLookupPayload, ax, path);
Está buena tu idea, pero se puede mejorar.
En un momento se usaban desde afuera los getElectrical, etc.... pero luego solo desde aca dentro en:
```
    const requests = {
      types: VehicleLookupService.getTypes(),
      lengthRanges: VehicleLookupService.getLengthRanges(),
      slides: VehicleLookupService.getSlides(),
      towings: VehicleLookupService.getTowings(),
      electricals: VehicleLookupService.getElectricals(),
    };  
 ```
 Entonces podes borrar todo menos getLookups, y usar todos los clients ahí dentro...

2023-05-06 21:26 UTC, gerardobrm approved these changes

2023-05-06 21:26 UTC, merged